package com.gojob.persistence.hibernatepojos;
// Generated 14 Jul, 2013 5:55:47 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.gojob.framework.persistence.AbstractPersistenceBean;

/**
 * CertificateMappingTbl generated by hbm2java
 */
@Entity
@Table(name="certificate_mapping_tbl"
    ,catalog="gojob"
)
public class CertificateMappingTbl  extends AbstractPersistenceBean {


     private Integer certmapId;
     private MappingGroup mappingGroup;
     private String certmapName;
     private String certmapInstName;
     private Double certmapScore;
     private Date certmapStartDate;
     private Date certmapEndDate;
     private String certmapDescription;

    public CertificateMappingTbl() {
    }

    public CertificateMappingTbl(MappingGroup mappingGroup, String certmapName, String certmapInstName, Double certmapScore, Date certmapStartDate, Date certmapEndDate, String certmapDescription) {
       this.mappingGroup = mappingGroup;
       this.certmapName = certmapName;
       this.certmapInstName = certmapInstName;
       this.certmapScore = certmapScore;
       this.certmapStartDate = certmapStartDate;
       this.certmapEndDate = certmapEndDate;
       this.certmapDescription = certmapDescription;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="certmap_id", unique=true, nullable=false)
    public Integer getCertmapId() {
        return this.certmapId;
    }
    
    public void setCertmapId(Integer certmapId) {
        this.certmapId = certmapId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mg_id")
    public MappingGroup getMappingGroup() {
        return this.mappingGroup;
    }
    
    public void setMappingGroup(MappingGroup mappingGroup) {
        this.mappingGroup = mappingGroup;
    }
    
    @Column(name="certmap_name", length=1000)
    public String getCertmapName() {
        return this.certmapName;
    }
    
    public void setCertmapName(String certmapName) {
        this.certmapName = certmapName;
    }
    
    @Column(name="certmap_inst_name", length=2000)
    public String getCertmapInstName() {
        return this.certmapInstName;
    }
    
    public void setCertmapInstName(String certmapInstName) {
        this.certmapInstName = certmapInstName;
    }
    
    @Column(name="certmap_score", precision=15, scale=3)
    public Double getCertmapScore() {
        return this.certmapScore;
    }
    
    public void setCertmapScore(Double certmapScore) {
        this.certmapScore = certmapScore;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="certmap_start_date", length=10)
    public Date getCertmapStartDate() {
        return this.certmapStartDate;
    }
    
    public void setCertmapStartDate(Date certmapStartDate) {
        this.certmapStartDate = certmapStartDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="certmap_end_date", length=10)
    public Date getCertmapEndDate() {
        return this.certmapEndDate;
    }
    
    public void setCertmapEndDate(Date certmapEndDate) {
        this.certmapEndDate = certmapEndDate;
    }
    
    @Column(name="certmap_description", length=500)
    public String getCertmapDescription() {
        return this.certmapDescription;
    }
    
    public void setCertmapDescription(String certmapDescription) {
        this.certmapDescription = certmapDescription;
    }




}


