package com.gojob.persistence.hibernatepojos;
// Generated 14 Jul, 2013 5:55:47 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.gojob.framework.persistence.AbstractPersistenceBean;

/**
 * CompanyTbl generated by hbm2java
 */
@Entity
@Table(name="company_tbl"
    ,catalog="gojob"
)
public class CompanyTbl  extends AbstractPersistenceBean {


     private Integer cmpId;
     private String cmpName;
     private Set<ExperienceMapping> experienceMappings = new HashSet<ExperienceMapping>(0);
     private Set<JobTbl> jobTbls = new HashSet<JobTbl>(0);

    public CompanyTbl() {
    }

    public CompanyTbl(String cmpName, Set<ExperienceMapping> experienceMappings, Set<JobTbl> jobTbls) {
       this.cmpName = cmpName;
       this.experienceMappings = experienceMappings;
       this.jobTbls = jobTbls;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="cmp_id", unique=true, nullable=false)
    public Integer getCmpId() {
        return this.cmpId;
    }
    
    public void setCmpId(Integer cmpId) {
        this.cmpId = cmpId;
    }
    
    @Column(name="cmp_name", length=1000)
    public String getCmpName() {
        return this.cmpName;
    }
    
    public void setCmpName(String cmpName) {
        this.cmpName = cmpName;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="companyTbl")
    public Set<ExperienceMapping> getExperienceMappings() {
        return this.experienceMappings;
    }
    
    public void setExperienceMappings(Set<ExperienceMapping> experienceMappings) {
        this.experienceMappings = experienceMappings;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="companyTbl")
    public Set<JobTbl> getJobTbls() {
        return this.jobTbls;
    }
    
    public void setJobTbls(Set<JobTbl> jobTbls) {
        this.jobTbls = jobTbls;
    }




}


