package com.gojob.persistence.hibernatepojos;
// Generated 14 Jul, 2013 5:55:47 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.gojob.framework.persistence.AbstractPersistenceBean;

/**
 * EducationTbl generated by hbm2java
 */
@Entity
@Table(name="education_tbl"
    ,catalog="gojob"
)
public class EducationTbl extends AbstractPersistenceBean {


     private Integer educationId;
     private MappingGroup mappingGroup;
     private Set<ProfileTbl> profileTbls = new HashSet<ProfileTbl>(0);

    public EducationTbl() {
    }

	
    public EducationTbl(MappingGroup mappingGroup) {
        this.mappingGroup = mappingGroup;
    }
    public EducationTbl(MappingGroup mappingGroup, Set<ProfileTbl> profileTbls) {
       this.mappingGroup = mappingGroup;
       this.profileTbls = profileTbls;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="education_id", unique=true, nullable=false)
    public Integer getEducationId() {
        return this.educationId;
    }
    
    public void setEducationId(Integer educationId) {
        this.educationId = educationId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mg_id", nullable=false)
    public MappingGroup getMappingGroup() {
        return this.mappingGroup;
    }
    
    public void setMappingGroup(MappingGroup mappingGroup) {
        this.mappingGroup = mappingGroup;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="educationTbl")
    public Set<ProfileTbl> getProfileTbls() {
        return this.profileTbls;
    }
    
    public void setProfileTbls(Set<ProfileTbl> profileTbls) {
        this.profileTbls = profileTbls;
    }




}


