package com.gojob.persistence.hibernatepojos;
// Generated 14 Jul, 2013 5:55:47 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.gojob.framework.persistence.AbstractPersistenceBean;

/**
 * EmployerProfileTbl generated by hbm2java
 */
@Entity
@Table(name="employer_profile_tbl"
    ,catalog="gojob"
)
public class EmployerProfileTbl  extends AbstractPersistenceBean {


     private Integer emppId;
     private ContactTbl contactTbl;
     private Byte consultancyFl;
     private String emppName;
     private String industries;

    public EmployerProfileTbl() {
    }

    public EmployerProfileTbl(ContactTbl contactTbl, Byte consultancyFl, String emppName, String industries) {
       this.contactTbl = contactTbl;
       this.consultancyFl = consultancyFl;
       this.emppName = emppName;
       this.industries = industries;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="empp_id", unique=true, nullable=false)
    public Integer getEmppId() {
        return this.emppId;
    }
    
    public void setEmppId(Integer emppId) {
        this.emppId = emppId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="contact_id")
    public ContactTbl getContactTbl() {
        return this.contactTbl;
    }
    
    public void setContactTbl(ContactTbl contactTbl) {
        this.contactTbl = contactTbl;
    }
    
    @Column(name="consultancy_fl")
    public Byte getConsultancyFl() {
        return this.consultancyFl;
    }
    
    public void setConsultancyFl(Byte consultancyFl) {
        this.consultancyFl = consultancyFl;
    }
    
    @Column(name="empp_name", length=300)
    public String getEmppName() {
        return this.emppName;
    }
    
    public void setEmppName(String emppName) {
        this.emppName = emppName;
    }
    
    @Column(name="industries", length=2000)
    public String getIndustries() {
        return this.industries;
    }
    
    public void setIndustries(String industries) {
        this.industries = industries;
    }




}


