package com.gojob.persistence.hibernatepojos;
// Generated 14 Jul, 2013 5:55:47 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.gojob.framework.persistence.AbstractPersistenceBean;

/**
 * GenderTbl generated by hbm2java
 */
@Entity
@Table(name="gender_tbl"
    ,catalog="gojob"
)
public class GenderTbl extends AbstractPersistenceBean {


     private Integer genderId;
     private String genderType;
     private Set<PersonalTbl> personalTbls = new HashSet<PersonalTbl>(0);

    public GenderTbl() {
    }

	
    public GenderTbl(String genderType) {
        this.genderType = genderType;
    }
    public GenderTbl(String genderType, Set personalTbls) {
       this.genderType = genderType;
       this.personalTbls = personalTbls;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="gender_id", unique=true, nullable=false)
    public Integer getGenderId() {
        return this.genderId;
    }
    
    public void setGenderId(Integer genderId) {
        this.genderId = genderId;
    }
    
    @Column(name="gender_type", nullable=false, length=10)
    public String getGenderType() {
        return this.genderType;
    }
    
    public void setGenderType(String genderType) {
        this.genderType = genderType;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="genderTbl")
    public Set<PersonalTbl> getPersonalTbls() {
        return this.personalTbls;
    }
    
    public void setPersonalTbls(Set<PersonalTbl> personalTbls) {
        this.personalTbls = personalTbls;
    }




}


