package com.gojob.persistence.hibernatepojos;
// Generated 14 Jul, 2013 5:55:47 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.gojob.framework.persistence.AbstractPersistenceBean;

/**
 * IndustryTbl generated by hbm2java
 */
@Entity
@Table(name="industry_tbl"
    ,catalog="gojob"
)
public class IndustryTbl  extends AbstractPersistenceBean {


     private Integer indId;
     private String indName;
     private Set<ProfessionalTbl> professionalTbls = new HashSet<ProfessionalTbl>(0);

    public IndustryTbl() {
    }

    public IndustryTbl(String indName, Set<ProfessionalTbl> professionalTbls) {
       this.indName = indName;
       this.professionalTbls = professionalTbls;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ind_id", unique=true, nullable=false)
    public Integer getIndId() {
        return this.indId;
    }
    
    public void setIndId(Integer indId) {
        this.indId = indId;
    }
    
    @Column(name="ind_name", length=1000)
    public String getIndName() {
        return this.indName;
    }
    
    public void setIndName(String indName) {
        this.indName = indName;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="industryTbl")
    public Set<ProfessionalTbl> getProfessionalTbls() {
        return this.professionalTbls;
    }
    
    public void setProfessionalTbls(Set<ProfessionalTbl> professionalTbls) {
        this.professionalTbls = professionalTbls;
    }




}


