package com.gojob.persistence.hibernatepojos;
// Generated 14 Jul, 2013 5:55:47 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.gojob.framework.persistence.AbstractPersistenceBean;

/**
 * InstituteTbl generated by hbm2java
 */
@Entity
@Table(name="institute_tbl"
    ,catalog="gojob"
)
public class InstituteTbl extends AbstractPersistenceBean {


     private Integer instId;
     private QualificationTbl qualificationTbl;
     private String instName;
     private Byte instParentFl;
     private Set<QualificationMapping> qualificationMappings = new HashSet<QualificationMapping>(0);

    public InstituteTbl() {
    }

	
    public InstituteTbl(QualificationTbl qualificationTbl) {
        this.qualificationTbl = qualificationTbl;
    }
    public InstituteTbl(QualificationTbl qualificationTbl, String instName, Byte instParentFl, Set<QualificationMapping> qualificationMappings) {
       this.qualificationTbl = qualificationTbl;
       this.instName = instName;
       this.instParentFl = instParentFl;
       this.qualificationMappings = qualificationMappings;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="inst_id", unique=true, nullable=false)
    public Integer getInstId() {
        return this.instId;
    }
    
    public void setInstId(Integer instId) {
        this.instId = instId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="qual_id", nullable=false)
    public QualificationTbl getQualificationTbl() {
        return this.qualificationTbl;
    }
    
    public void setQualificationTbl(QualificationTbl qualificationTbl) {
        this.qualificationTbl = qualificationTbl;
    }
    
    @Column(name="inst_name", length=500)
    public String getInstName() {
        return this.instName;
    }
    
    public void setInstName(String instName) {
        this.instName = instName;
    }
    
    @Column(name="inst_parent_fl")
    public Byte getInstParentFl() {
        return this.instParentFl;
    }
    
    public void setInstParentFl(Byte instParentFl) {
        this.instParentFl = instParentFl;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="instituteTbl")
    public Set<QualificationMapping> getQualificationMappings() {
        return this.qualificationMappings;
    }
    
    public void setQualificationMappings(Set<QualificationMapping> qualificationMappings) {
        this.qualificationMappings = qualificationMappings;
    }




}


