package com.gojob.persistence.hibernatepojos;
// Generated 14 Jul, 2013 5:55:47 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.gojob.framework.persistence.AbstractPersistenceBean;

/**
 * LinkTbl generated by hbm2java
 */
@Entity
@Table(name="link_tbl"
    ,catalog="gojob"
)
public class LinkTbl  extends AbstractPersistenceBean{


     private Integer linkId;
     private MappingGroup mappingGroup;
     private LinktypeTbl linktypeTbl;
     private String linkUrl;

    public LinkTbl() {
    }

	
    public LinkTbl(MappingGroup mappingGroup, LinktypeTbl linktypeTbl) {
        this.mappingGroup = mappingGroup;
        this.linktypeTbl = linktypeTbl;
    }
    public LinkTbl(MappingGroup mappingGroup, LinktypeTbl linktypeTbl, String linkUrl) {
       this.mappingGroup = mappingGroup;
       this.linktypeTbl = linktypeTbl;
       this.linkUrl = linkUrl;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="link_id", unique=true, nullable=false)
    public Integer getLinkId() {
        return this.linkId;
    }
    
    public void setLinkId(Integer linkId) {
        this.linkId = linkId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mg_id", nullable=false)
    public MappingGroup getMappingGroup() {
        return this.mappingGroup;
    }
    
    public void setMappingGroup(MappingGroup mappingGroup) {
        this.mappingGroup = mappingGroup;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="link_type_id", nullable=false)
    public LinktypeTbl getLinktypeTbl() {
        return this.linktypeTbl;
    }
    
    public void setLinktypeTbl(LinktypeTbl linktypeTbl) {
        this.linktypeTbl = linktypeTbl;
    }
    
    @Column(name="link_url", length=1000)
    public String getLinkUrl() {
        return this.linkUrl;
    }
    
    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl;
    }




}


