package com.gojob.persistence.hibernatepojos;
// Generated 14 Jul, 2013 5:55:47 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.gojob.framework.persistence.AbstractPersistenceBean;

/**
 * LinktypeTbl generated by hbm2java
 */
@Entity
@Table(name="linktype_tbl"
    ,catalog="gojob"
)
public class LinktypeTbl  extends AbstractPersistenceBean {


     private Integer linkTypeId;
     private String linkTypeName;
     private Set<LinkTbl> linkTbls = new HashSet<LinkTbl>(0);

    public LinktypeTbl() {
    }

    public LinktypeTbl(String linkTypeName, Set<LinkTbl> linkTbls) {
       this.linkTypeName = linkTypeName;
       this.linkTbls = linkTbls;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="link_type_id", unique=true, nullable=false)
    public Integer getLinkTypeId() {
        return this.linkTypeId;
    }
    
    public void setLinkTypeId(Integer linkTypeId) {
        this.linkTypeId = linkTypeId;
    }
    
    @Column(name="link_type_name", length=500)
    public String getLinkTypeName() {
        return this.linkTypeName;
    }
    
    public void setLinkTypeName(String linkTypeName) {
        this.linkTypeName = linkTypeName;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="linktypeTbl")
    public Set<LinkTbl> getLinkTbls() {
        return this.linkTbls;
    }
    
    public void setLinkTbls(Set<LinkTbl> linkTbls) {
        this.linkTbls = linkTbls;
    }




}


