package com.gojob.persistence.hibernatepojos;
// Generated 14 Jul, 2013 5:55:47 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.gojob.framework.persistence.AbstractPersistenceBean;

/**
 * LocationTypeTbl generated by hbm2java
 */
@Entity
@Table(name="location_type_tbl"
    ,catalog="gojob"
)
public class LocationTypeTbl extends AbstractPersistenceBean {


     private Integer locTypeId;
     private String locTypeName;
     private Set<LocationTbl> locationTbls = new HashSet<LocationTbl>(0);

    public LocationTypeTbl() {
    }

    public LocationTypeTbl(String locTypeName, Set<LocationTbl> locationTbls) {
       this.locTypeName = locTypeName;
       this.locationTbls = locationTbls;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="loc_type_id", unique=true, nullable=false)
    public Integer getLocTypeId() {
        return this.locTypeId;
    }
    
    public void setLocTypeId(Integer locTypeId) {
        this.locTypeId = locTypeId;
    }
    
    @Column(name="loc_type_name", length=2000)
    public String getLocTypeName() {
        return this.locTypeName;
    }
    
    public void setLocTypeName(String locTypeName) {
        this.locTypeName = locTypeName;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="locationTypeTbl")
    public Set<LocationTbl> getLocationTbls() {
        return this.locationTbls;
    }
    
    public void setLocationTbls(Set<LocationTbl> locationTbls) {
        this.locationTbls = locationTbls;
    }




}


