package com.gojob.persistence.hibernatepojos;
// Generated 14 Jul, 2013 5:55:47 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.gojob.framework.persistence.AbstractPersistenceBean;

/**
 * ProfessionalTbl generated by hbm2java
 */
@Entity
@Table(name="professional_tbl"
    ,catalog="gojob"
)
public class ProfessionalTbl  extends AbstractPersistenceBean {


     private Integer prfId;
     private IndustryTbl industryTbl;
     private TechnologyTbl technologyTbl;
     private int exmMgId;
     private int skillMgId;
     private int certmapMgId;
     private String prfResume;
     private String prfTotalWorkEx;
     private Set<ProfileTbl> profileTbls = new HashSet<ProfileTbl>(0);

    public ProfessionalTbl() {
    }

	
    public ProfessionalTbl(IndustryTbl industryTbl, TechnologyTbl technologyTbl, int exmMgId, int skillMgId, int certmapMgId) {
        this.industryTbl = industryTbl;
        this.technologyTbl = technologyTbl;
        this.exmMgId = exmMgId;
        this.skillMgId = skillMgId;
        this.certmapMgId = certmapMgId;
    }
    public ProfessionalTbl(IndustryTbl industryTbl, TechnologyTbl technologyTbl, int exmMgId, int skillMgId, int certmapMgId, String prfResume, String prfTotalWorkEx, Set<ProfileTbl> profileTbls) {
       this.industryTbl = industryTbl;
       this.technologyTbl = technologyTbl;
       this.exmMgId = exmMgId;
       this.skillMgId = skillMgId;
       this.certmapMgId = certmapMgId;
       this.prfResume = prfResume;
       this.prfTotalWorkEx = prfTotalWorkEx;
       this.profileTbls = profileTbls;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="prf_id", unique=true, nullable=false)
    public Integer getPrfId() {
        return this.prfId;
    }
    
    public void setPrfId(Integer prfId) {
        this.prfId = prfId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ind_id", nullable=false)
    public IndustryTbl getIndustryTbl() {
        return this.industryTbl;
    }
    
    public void setIndustryTbl(IndustryTbl industryTbl) {
        this.industryTbl = industryTbl;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tech_id", nullable=false)
    public TechnologyTbl getTechnologyTbl() {
        return this.technologyTbl;
    }
    
    public void setTechnologyTbl(TechnologyTbl technologyTbl) {
        this.technologyTbl = technologyTbl;
    }
    
    @Column(name="exm_mg_id", nullable=false)
    public int getExmMgId() {
        return this.exmMgId;
    }
    
    public void setExmMgId(int exmMgId) {
        this.exmMgId = exmMgId;
    }
    
    @Column(name="skill_mg_id", nullable=false)
    public int getSkillMgId() {
        return this.skillMgId;
    }
    
    public void setSkillMgId(int skillMgId) {
        this.skillMgId = skillMgId;
    }
    
    @Column(name="certmap_mg_id", nullable=false)
    public int getCertmapMgId() {
        return this.certmapMgId;
    }
    
    public void setCertmapMgId(int certmapMgId) {
        this.certmapMgId = certmapMgId;
    }
    
    @Column(name="prf_resume", length=1000)
    public String getPrfResume() {
        return this.prfResume;
    }
    
    public void setPrfResume(String prfResume) {
        this.prfResume = prfResume;
    }
    
    @Column(name="prf_total_work_ex", length=200)
    public String getPrfTotalWorkEx() {
        return this.prfTotalWorkEx;
    }
    
    public void setPrfTotalWorkEx(String prfTotalWorkEx) {
        this.prfTotalWorkEx = prfTotalWorkEx;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="professionalTbl")
    public Set<ProfileTbl> getProfileTbls() {
        return this.profileTbls;
    }
    
    public void setProfileTbls(Set<ProfileTbl> profileTbls) {
        this.profileTbls = profileTbls;
    }




}


