package com.gojob.persistence.hibernatepojos;
// Generated 14 Jul, 2013 5:55:47 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.gojob.framework.persistence.AbstractPersistenceBean;

/**
 * ProfileTbl generated by hbm2java
 */
@Entity
@Table(name="profile_tbl"
    ,catalog="gojob"
)
public class ProfileTbl extends AbstractPersistenceBean {


     private Integer profId;
     private QualificationTbl qualificationTbl;
     private UserTbl userTbl;
     private PersonalTbl personalTbl;
     private ProfessionalTbl professionalTbl;
     private EducationTbl educationTbl;
     private String resumeId;
     private Integer linkMgId;
     private String profName;
     private Date createDate;
     private Date updateDate;

    public ProfileTbl() {
    }

    public ProfileTbl(QualificationTbl qualificationTbl, UserTbl userTbl, PersonalTbl personalTbl, ProfessionalTbl professionalTbl, EducationTbl educationTbl, String resumeId, Integer linkMgId, String profName, Date createDate, Date updateDate) {
       this.qualificationTbl = qualificationTbl;
       this.userTbl = userTbl;
       this.personalTbl = personalTbl;
       this.professionalTbl = professionalTbl;
       this.educationTbl = educationTbl;
       this.resumeId = resumeId;
       this.linkMgId = linkMgId;
       this.profName = profName;
       this.createDate = createDate;
       this.updateDate = updateDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="prof_id", unique=true, nullable=false)
    public Integer getProfId() {
        return this.profId;
    }
    
    public void setProfId(Integer profId) {
        this.profId = profId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="qual_id")
    public QualificationTbl getQualificationTbl() {
        return this.qualificationTbl;
    }
    
    public void setQualificationTbl(QualificationTbl qualificationTbl) {
        this.qualificationTbl = qualificationTbl;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id")
    public UserTbl getUserTbl() {
        return this.userTbl;
    }
    
    public void setUserTbl(UserTbl userTbl) {
        this.userTbl = userTbl;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="per_id")
    public PersonalTbl getPersonalTbl() {
        return this.personalTbl;
    }
    
    public void setPersonalTbl(PersonalTbl personalTbl) {
        this.personalTbl = personalTbl;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="prf_id")
    public ProfessionalTbl getProfessionalTbl() {
        return this.professionalTbl;
    }
    
    public void setProfessionalTbl(ProfessionalTbl professionalTbl) {
        this.professionalTbl = professionalTbl;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="education_id")
    public EducationTbl getEducationTbl() {
        return this.educationTbl;
    }
    
    public void setEducationTbl(EducationTbl educationTbl) {
        this.educationTbl = educationTbl;
    }
    
    @Column(name="resume_id", length=300)
    public String getResumeId() {
        return this.resumeId;
    }
    
    public void setResumeId(String resumeId) {
        this.resumeId = resumeId;
    }
    
    @Column(name="link_mg_id")
    public Integer getLinkMgId() {
        return this.linkMgId;
    }
    
    public void setLinkMgId(Integer linkMgId) {
        this.linkMgId = linkMgId;
    }
    
    @Column(name="prof_name", length=1000)
    public String getProfName() {
        return this.profName;
    }
    
    public void setProfName(String profName) {
        this.profName = profName;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="create_date", length=10)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="update_date", length=10)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }




}


