package com.gojob.persistence.hibernatepojos;
// Generated 14 Jul, 2013 5:55:47 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.gojob.framework.persistence.AbstractPersistenceBean;

/**
 * QualificationMapping generated by hbm2java
 */
@Entity
@Table(name="qualification_mapping"
    ,catalog="gojob"
)
public class QualificationMapping extends AbstractPersistenceBean {


     private Integer qmId;
     private QualificationTbl qualificationTbl;
     private LocationTbl locationTbl;
     private InstituteTbl instituteTbl;
     private int qmgId;
     private int qmParentInstId;
     private String qmInstName;
     private Date qmStartDate;
     private Date qmEndDate;
     private Double qmMarksPercentage;
     private Double qmCgpa;
     private String qmParentInstName;

    public QualificationMapping() {
    }

	
    public QualificationMapping(QualificationTbl qualificationTbl, LocationTbl locationTbl, InstituteTbl instituteTbl, int qmgId, int qmParentInstId) {
        this.qualificationTbl = qualificationTbl;
        this.locationTbl = locationTbl;
        this.instituteTbl = instituteTbl;
        this.qmgId = qmgId;
        this.qmParentInstId = qmParentInstId;
    }
    public QualificationMapping(QualificationTbl qualificationTbl, LocationTbl locationTbl, InstituteTbl instituteTbl, int qmgId, int qmParentInstId, String qmInstName, Date qmStartDate, Date qmEndDate, Double qmMarksPercentage, Double qmCgpa, String qmParentInstName) {
       this.qualificationTbl = qualificationTbl;
       this.locationTbl = locationTbl;
       this.instituteTbl = instituteTbl;
       this.qmgId = qmgId;
       this.qmParentInstId = qmParentInstId;
       this.qmInstName = qmInstName;
       this.qmStartDate = qmStartDate;
       this.qmEndDate = qmEndDate;
       this.qmMarksPercentage = qmMarksPercentage;
       this.qmCgpa = qmCgpa;
       this.qmParentInstName = qmParentInstName;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="qm_id", unique=true, nullable=false)
    public Integer getQmId() {
        return this.qmId;
    }
    
    public void setQmId(Integer qmId) {
        this.qmId = qmId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="qual_id", nullable=false)
    public QualificationTbl getQualificationTbl() {
        return this.qualificationTbl;
    }
    
    public void setQualificationTbl(QualificationTbl qualificationTbl) {
        this.qualificationTbl = qualificationTbl;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="loc_id", nullable=false)
    public LocationTbl getLocationTbl() {
        return this.locationTbl;
    }
    
    public void setLocationTbl(LocationTbl locationTbl) {
        this.locationTbl = locationTbl;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="inst_id", nullable=false)
    public InstituteTbl getInstituteTbl() {
        return this.instituteTbl;
    }
    
    public void setInstituteTbl(InstituteTbl instituteTbl) {
        this.instituteTbl = instituteTbl;
    }
    
    @Column(name="qmg_id", nullable=false)
    public int getQmgId() {
        return this.qmgId;
    }
    
    public void setQmgId(int qmgId) {
        this.qmgId = qmgId;
    }
    
    @Column(name="qm_parent_inst_id", nullable=false)
    public int getQmParentInstId() {
        return this.qmParentInstId;
    }
    
    public void setQmParentInstId(int qmParentInstId) {
        this.qmParentInstId = qmParentInstId;
    }
    
    @Column(name="qm_inst_name", length=500)
    public String getQmInstName() {
        return this.qmInstName;
    }
    
    public void setQmInstName(String qmInstName) {
        this.qmInstName = qmInstName;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="qm_start_date", length=10)
    public Date getQmStartDate() {
        return this.qmStartDate;
    }
    
    public void setQmStartDate(Date qmStartDate) {
        this.qmStartDate = qmStartDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="qm_end_date", length=10)
    public Date getQmEndDate() {
        return this.qmEndDate;
    }
    
    public void setQmEndDate(Date qmEndDate) {
        this.qmEndDate = qmEndDate;
    }
    
    @Column(name="qm_marks_percentage", precision=20, scale=3)
    public Double getQmMarksPercentage() {
        return this.qmMarksPercentage;
    }
    
    public void setQmMarksPercentage(Double qmMarksPercentage) {
        this.qmMarksPercentage = qmMarksPercentage;
    }
    
    @Column(name="qm_cgpa", precision=20, scale=3)
    public Double getQmCgpa() {
        return this.qmCgpa;
    }
    
    public void setQmCgpa(Double qmCgpa) {
        this.qmCgpa = qmCgpa;
    }
    
    @Column(name="qm_parent_inst_name", length=500)
    public String getQmParentInstName() {
        return this.qmParentInstName;
    }
    
    public void setQmParentInstName(String qmParentInstName) {
        this.qmParentInstName = qmParentInstName;
    }




}


