package com.gojob.persistence.hibernatepojos;
// Generated 14 Jul, 2013 5:55:47 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.gojob.framework.persistence.AbstractPersistenceBean;

/**
 * SkillMapping generated by hbm2java
 */
@Entity
@Table(name="skill_mapping"
    ,catalog="gojob"
)
public class SkillMapping extends AbstractPersistenceBean {


     private Integer skillmapId;
     private SkilltypeTbl skilltypeTbl;
     private MappingGroup mappingGroup;
     private String skillName;
     private Date skillStartDate;
     private Date skillEndDate;
     private String skillDescription;

    public SkillMapping() {
    }

	
    public SkillMapping(SkilltypeTbl skilltypeTbl, MappingGroup mappingGroup) {
        this.skilltypeTbl = skilltypeTbl;
        this.mappingGroup = mappingGroup;
    }
    public SkillMapping(SkilltypeTbl skilltypeTbl, MappingGroup mappingGroup, String skillName, Date skillStartDate, Date skillEndDate, String skillDescription) {
       this.skilltypeTbl = skilltypeTbl;
       this.mappingGroup = mappingGroup;
       this.skillName = skillName;
       this.skillStartDate = skillStartDate;
       this.skillEndDate = skillEndDate;
       this.skillDescription = skillDescription;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="skillmap_id", unique=true, nullable=false)
    public Integer getSkillmapId() {
        return this.skillmapId;
    }
    
    public void setSkillmapId(Integer skillmapId) {
        this.skillmapId = skillmapId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="skill_type_id", nullable=false)
    public SkilltypeTbl getSkilltypeTbl() {
        return this.skilltypeTbl;
    }
    
    public void setSkilltypeTbl(SkilltypeTbl skilltypeTbl) {
        this.skilltypeTbl = skilltypeTbl;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mg_id", nullable=false)
    public MappingGroup getMappingGroup() {
        return this.mappingGroup;
    }
    
    public void setMappingGroup(MappingGroup mappingGroup) {
        this.mappingGroup = mappingGroup;
    }
    
    @Column(name="skill_name", length=400)
    public String getSkillName() {
        return this.skillName;
    }
    
    public void setSkillName(String skillName) {
        this.skillName = skillName;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="skill_start_date", length=10)
    public Date getSkillStartDate() {
        return this.skillStartDate;
    }
    
    public void setSkillStartDate(Date skillStartDate) {
        this.skillStartDate = skillStartDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="skill_end_date", length=10)
    public Date getSkillEndDate() {
        return this.skillEndDate;
    }
    
    public void setSkillEndDate(Date skillEndDate) {
        this.skillEndDate = skillEndDate;
    }
    
    @Column(name="skill_description", length=1000)
    public String getSkillDescription() {
        return this.skillDescription;
    }
    
    public void setSkillDescription(String skillDescription) {
        this.skillDescription = skillDescription;
    }




}


