package com.gojob.persistence.hibernatepojos;
// Generated 14 Jul, 2013 5:55:47 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.gojob.framework.persistence.AbstractPersistenceBean;

/**
 * UserTbl generated by hbm2java
 */
@Entity
@Table(name="user_tbl"
    ,catalog="gojob"
)
public class UserTbl extends AbstractPersistenceBean {


     private Integer userId;
     private UserRoleTbl userRoleTbl;
     private String userName;
     private String password;
     private Byte disabledFl;
     private Set<JobTbl> jobTbls = new HashSet<JobTbl>(0);
     private Set<JobViewTbl> jobViewTbls = new HashSet<JobViewTbl>(0);
     private Set<ProfileTbl> profileTbls = new HashSet<ProfileTbl>(0);

    public UserTbl() {
    }

    public UserTbl(UserRoleTbl userRoleTbl, String userName, String password, Byte disabledFl, Set<JobTbl> jobTbls, Set<JobViewTbl> jobViewTbls, Set<ProfileTbl> profileTbls) {
       this.userRoleTbl = userRoleTbl;
       this.userName = userName;
       this.password = password;
       this.disabledFl = disabledFl;
       this.jobTbls = jobTbls;
       this.jobViewTbls = jobViewTbls;
       this.profileTbls = profileTbls;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="user_id", unique=true, nullable=false)
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_role_id")
    public UserRoleTbl getUserRoleTbl() {
        return this.userRoleTbl;
    }
    
    public void setUserRoleTbl(UserRoleTbl userRoleTbl) {
        this.userRoleTbl = userRoleTbl;
    }
    
    @Column(name="user_name", length=300)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    
    @Column(name="password", length=100)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="disabled_fl")
    public Byte getDisabledFl() {
        return this.disabledFl;
    }
    
    public void setDisabledFl(Byte disabledFl) {
        this.disabledFl = disabledFl;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="userTbl")
    public Set<JobTbl> getJobTbls() {
        return this.jobTbls;
    }
    
    public void setJobTbls(Set<JobTbl> jobTbls) {
        this.jobTbls = jobTbls;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="userTbl")
    public Set<JobViewTbl> getJobViewTbls() {
        return this.jobViewTbls;
    }
    
    public void setJobViewTbls(Set<JobViewTbl> jobViewTbls) {
        this.jobViewTbls = jobViewTbls;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="userTbl")
    public Set<ProfileTbl> getProfileTbls() {
        return this.profileTbls;
    }
    
    public void setProfileTbls(Set<ProfileTbl> profileTbls) {
        this.profileTbls = profileTbls;
    }




}


