package com.gojob.persistence.hibernatepojos;
// Generated 14 Jul, 2013 5:55:47 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.gojob.framework.persistence.AbstractPersistenceBean;

/**
 * UserRoleTbl generated by hbm2java
 */
@Entity
@Table(name="user_role_tbl"
    ,catalog="gojob"
)
public class UserRoleTbl  extends AbstractPersistenceBean{


     private Integer userRoleId;
     private String userRoleName;
     private Byte deleteFl;
     private Set<UserTbl> userTbls = new HashSet<UserTbl>(0);

    public UserRoleTbl() {
    }

    public UserRoleTbl(String userRoleName, Byte deleteFl, Set<UserTbl> userTbls) {
       this.userRoleName = userRoleName;
       this.deleteFl = deleteFl;
       this.userTbls = userTbls;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="user_role_id", unique=true, nullable=false)
    public Integer getUserRoleId() {
        return this.userRoleId;
    }
    
    public void setUserRoleId(Integer userRoleId) {
        this.userRoleId = userRoleId;
    }
    
    @Column(name="user_role_name", length=300)
    public String getUserRoleName() {
        return this.userRoleName;
    }
    
    public void setUserRoleName(String userRoleName) {
        this.userRoleName = userRoleName;
    }
    
    @Column(name="delete_fl")
    public Byte getDeleteFl() {
        return this.deleteFl;
    }
    
    public void setDeleteFl(Byte deleteFl) {
        this.deleteFl = deleteFl;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="userRoleTbl")
    public Set<UserTbl> getUserTbls() {
        return this.userTbls;
    }
    
    public void setUserTbls(Set<UserTbl> userTbls) {
        this.userTbls = userTbls;
    }




}


